-- Curriculum Catalog v0.1. Universal layer; assumes base `sources` exists.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS subjects (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), code varchar(100) UNIQUE NOT NULL, name varchar(200) NOT NULL, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS grade_levels (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), grade integer UNIQUE NOT NULL CHECK(grade BETWEEN 1 AND 11), education_level varchar(100) NOT NULL, label varchar(100));
CREATE TABLE IF NOT EXISTS curricula (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), subject_id uuid NOT NULL REFERENCES subjects(id), grade_level_id uuid NOT NULL REFERENCES grade_levels(id), level varchar(100) NOT NULL DEFAULT 'basic', title varchar(500) NOT NULL, version varchar(100) NOT NULL DEFAULT 'v1', valid_from date, valid_until date, status varchar(50) NOT NULL DEFAULT 'current', official_source_id uuid REFERENCES sources(id), review_status varchar(50) NOT NULL DEFAULT 'draft', metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(subject_id,grade_level_id,level,version));
CREATE TABLE IF NOT EXISTS curriculum_units (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), curriculum_id uuid NOT NULL REFERENCES curricula(id) ON DELETE CASCADE, title varchar(500) NOT NULL, order_index integer NOT NULL, recommended_hours integer, description text, source_reference text, review_status varchar(50) NOT NULL DEFAULT 'draft', UNIQUE(curriculum_id,order_index));
CREATE TABLE IF NOT EXISTS topics (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), unit_id uuid NOT NULL REFERENCES curriculum_units(id) ON DELETE CASCADE, parent_topic_id uuid REFERENCES topics(id), title varchar(500) NOT NULL, aliases jsonb NOT NULL DEFAULT '[]'::jsonb, order_index integer NOT NULL, recommended_hours integer, topic_type varchar(100) NOT NULL DEFAULT 'new_content', description text, default_lesson_blueprint jsonb NOT NULL DEFAULT '{}'::jsonb, typical_misconceptions jsonb NOT NULL DEFAULT '[]'::jsonb, essential_questions jsonb NOT NULL DEFAULT '[]'::jsonb, reflection_patterns jsonb NOT NULL DEFAULT '[]'::jsonb, assessment_skills jsonb NOT NULL DEFAULT '[]'::jsonb, difficulty_level integer CHECK(difficulty_level BETWEEN 1 AND 5), abstraction_level integer CHECK(abstraction_level BETWEEN 1 AND 5), prerequisite_topic_ids jsonb NOT NULL DEFAULT '[]'::jsonb, review_status varchar(50) NOT NULL DEFAULT 'draft', metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, UNIQUE(unit_id,order_index));
CREATE TABLE IF NOT EXISTS learning_outcomes (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), subject_id uuid NOT NULL REFERENCES subjects(id), grade_level_id uuid REFERENCES grade_levels(id), outcome_type varchar(100) NOT NULL, outcome_subtype varchar(100), text text NOT NULL, source_reference text, review_status varchar(50) NOT NULL DEFAULT 'draft');
CREATE TABLE IF NOT EXISTS topic_outcomes (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), topic_id uuid NOT NULL REFERENCES topics(id) ON DELETE CASCADE, outcome_id uuid NOT NULL REFERENCES learning_outcomes(id) ON DELETE CASCADE, priority integer NOT NULL DEFAULT 1, UNIQUE(topic_id,outcome_id));
CREATE TABLE IF NOT EXISTS concepts (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), subject_id uuid NOT NULL REFERENCES subjects(id), term varchar(300) NOT NULL, definition_reference text, notes text, UNIQUE(subject_id,term));
CREATE TABLE IF NOT EXISTS topic_concepts (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), topic_id uuid NOT NULL REFERENCES topics(id) ON DELETE CASCADE, concept_id uuid NOT NULL REFERENCES concepts(id) ON DELETE CASCADE, importance varchar(50) NOT NULL DEFAULT 'required', UNIQUE(topic_id,concept_id));
CREATE TABLE IF NOT EXISTS skills (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), code varchar(100) UNIQUE NOT NULL, name varchar(300) NOT NULL, category varchar(100) NOT NULL, description text);
CREATE TABLE IF NOT EXISTS topic_skills (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), topic_id uuid NOT NULL REFERENCES topics(id) ON DELETE CASCADE, skill_id uuid NOT NULL REFERENCES skills(id) ON DELETE CASCADE, priority integer NOT NULL DEFAULT 1, UNIQUE(topic_id,skill_id));
CREATE TABLE IF NOT EXISTS exam_links (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), topic_id uuid NOT NULL REFERENCES topics(id) ON DELETE CASCADE, exam varchar(100) NOT NULL, exam_year integer, exam_section varchar(300), task_types jsonb NOT NULL DEFAULT '[]'::jsonb, codifier_reference text, importance varchar(50) NOT NULL DEFAULT 'normal');
CREATE TABLE IF NOT EXISTS topic_sources (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), topic_id uuid NOT NULL REFERENCES topics(id) ON DELETE CASCADE, source_id uuid NOT NULL REFERENCES sources(id) ON DELETE CASCADE, source_role varchar(100) NOT NULL, section varchar(500), pages varchar(100), priority integer NOT NULL DEFAULT 100, chunk_filters jsonb NOT NULL DEFAULT '{}'::jsonb, notes text, UNIQUE(topic_id,source_id,source_role));
CREATE INDEX IF NOT EXISTS ix_topics_title ON topics(title);
CREATE INDEX IF NOT EXISTS ix_curricula_status ON curricula(status);
CREATE INDEX IF NOT EXISTS ix_exam_links_exam_year ON exam_links(exam,exam_year);
CREATE INDEX IF NOT EXISTS ix_topic_sources_role_priority ON topic_sources(source_role,priority);
